it/urls.py
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls import include, url
from portal.views import profile
from portal.auth.forms import LoginForm


urlpatterns = [
    url(r'^', include(
        'portal.maintenance.urls', namespace='maintenance')),
    url(r'^profile/$', profile, name='profile'),

    url(r'^admin/', include('portal.maintenance.admin.urls', namespace='admin')),

    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/admin/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^applications/', include([
        url(r'^$', views.applications.index, name='index'),

        url(r'^(?P<pk>\d+)/', include([
            url(r'^$', views.applications.edit, name='edit'),
            url(r'^approve$', views.applications.approve, name='approve'),
            url(r'^reject$', views.applications.reject, name='reject'),
        ])),

        url(r'^(?P<reference>[^/]+).pdf$',
            views.applications.download, name='download'),
    ], namespace='applications')),

    url(r'^applications.csv', views.applications.rota, name='rota'),

    url(r'^facilities/', include([
        url(r'^$', views.facilities.index, name='index'),
        url(r'^new$', views.facilities.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.facilities.edit, name='edit'),
    ], namespace='facilities')),

    url(r'^call/new$', views.call_for_proposals, name='call_for_proposals'),

    url(r'calls/', include([
        url(r'^$', views.calls.index, name='index'),
        url(r'^new$', views.calls.add, name='add'),
        url(r'^(?P<pk>\d+)/', views.calls.edit, name='edit'),
    ], namespace='calls')),

    url(r'^telescopes/', include([
        url(r'^$', views.telescopes.index, name='index'),
        url(r'^new$', views.telescopes.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.telescopes.edit, name='edit'),
    ], namespace='telescopes')),

    url(r'^instruments/', include([
        url(r'^$', views.instruments.index, name='index'),
        url(r'^new$', views.instruments.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.instruments.edit, name='edit'),
    ], namespace='instruments')),

    url(r'^users/', include([
        url(r'^$', views.users.index, name='index'),
        url(r'^new$', views.users.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.users.edit, name='edit'),
    ], namespace='users')),

    url(r'^groups/', include([
        url(r'^$', views.groups.index, name='index'),
        url(r'^new$', views.groups.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.groups.edit, name='edit'),
    ], namespace='groups')),

    url(r'^sites/', include([
        url(r'^$', views.sites.index, name='index'),
        url(r'^new$', views.sites.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.sites.edit, name='edit'),
    ], namespace='sites')),

    # Only light pollution reports for now, but that might change later.
    url(r'^reports/', include([
        url(r'^new$', views.reports.create, name='create'),
    ], namespace='reports')),

    url(r'^calendar/$', views.calendar, name='calendar'),
]

portal/auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import register, activate
from .forms import LoginForm


urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^activate/$', activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),

    url(r'^password_reset/$', views.password_reset,
        {'template_name': 'auth/password_reset_form.html',
            'email_template_name': 'auth/emails/password_reset.txt',
            'subject_template_name': 'auth/emails/password_reset_subject.txt'}, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        {'template_name': 'auth/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm,
        {'template_name': 'auth/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.password_reset_complete,
        {'template_name': 'auth/password_reset_complete.html'}, name='password_reset_complete'),
]

portal/urls.py
from django.conf import settings
from django.conf.urls import include, url
from portal import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^telescopes/(?P<pk>\d+)$', views.telescope, name='telescope'),
    url(r'^instruments/(?P<pk>\d+)$', views.instrument, name='instrument'),
    url(r'^applications/', include('portal.applications.urls', namespace='applications')),
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^admin/', include('portal.admin.urls', namespace='admin')),

    url(r'^admin/maintenance/', include(
        'portal.maintenance.urls', namespace='maintenance')),

    url(r'^', include('portal.auth.urls')),

    url(r'^o/authorize/$', views.AuthView.as_view(), name='authorize'),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/me$', views.ApiEndpoint.as_view()),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/admin/views/applications.py
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.template.loader import render_to_string
from django.http import HttpResponse
from portal.models import Application, Call
from portal.applications.saao import SAAOApplication
from portal.applications.lcogt import LCOGTApplication
from portal.applications.kmtnet import KMTNETApplication
from portal.admin.forms import EmailForm, AssignCallForm


@login_required
def index(request):
    if not (request.user.is_staff and
            request.user.has_perm('portal.view_application')):
        raise PermissionDenied

    applications = Application.objects.exclude(state='draft')
    if 'state' in request.GET:
        applications = applications.filter(state=request.GET['state'])
    if 'call' in request.GET:
        applications = applications.filter(call=request.GET['call'])

    return render(request, 'admin/applications/index.html', {
        'applications': applications,
        'calls': Call.objects.all(),
    })


@login_required
def edit(request, pk):
    if not (request.user.is_staff and
            request.user.has_perm('portal.view_application')):
        raise PermissionDenied

    application = get_object_or_404(Application, pk=pk)

    if request.method == 'POST':
        if not request.user.has_perm('portal.change_application'):
            raise PermissionDenied

        if '_assign' in request.POST:
            form = AssignCallForm(application, request.POST)

            if form.is_valid():
                application.call_id = form.cleaned_data['call']
                application.save()

                messages.success(request,
                    'The application was successfully assigned to a call.')

        elif '_revert' in request.POST:
            application.state = 'draft'
            application.save()

            messages.success(request,
                'The application was successfully reverted.')

        return redirect('admin:applications:index')

    context = {'application': application}
    if not application.call:
        context.update({'form': AssignCallForm(application)})

    if application.facility.name == 'SAAO':
        template_name = 'admin/applications/saao.html'
    elif application.facility.name == 'LCO':
        template_name = 'admin/applications/lcogt.html'
    elif application.facility.name == 'KMTNET':
        template_name = 'admin/applications/kmtnet.html'

    return render(request, template_name, context)


@login_required
def approve(request, pk):
    if not (request.user.is_staff and
            request.user.has_perm('portal.approve_application')):
        raise PermissionDenied

    application = get_object_or_404(Application, pk=pk,
        state='submitted')
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if '_notify' in request.POST and form.is_valid():
            application.approve()
            application.save()

            # Get coordinators so the we can BCC them for auditing purposes.
            coordinators = Group.objects.get(name='Coordinators').user_set.all()

            form.send(
                from_='observer@saao.ac.za',
                bcc=[c.email for c in coordinators],
            )
            messages.success(request, 'The observer has been notified of the update.')
            return redirect('admin:applications:index')
        elif '_notify' not in request.POST:
            application.approve()
            application.save()
            messages.success(request, 'The application has been approved.')
            return redirect('admin:applications:index')
    else:
        message = render_to_string('applications/saao/emails/approved.txt', {
            'application': application
        })
        form = EmailForm(initial={
            'to': application.email,
            'cc': ','.join(a.email for a in application.applicants.all()
                if a.email != application.email),
            'subject': '[{}] Telescope Time Application'.format(
                application),
            'message': message,
        })
    return render(request, 'admin/applications/approve.html', {
        'application': application, 'form': form})


@login_required
def reject(request, pk):
    if not (request.user.is_staff and
            request.user.has_perm('portal.reject_application')):
        raise PermissionDenied

    application = get_object_or_404(Application, pk=pk,
        state='submitted')
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if '_notify' in request.POST and form.is_valid():
            application.reject()
            application.save()
            form.send(from_='observer@saao.ac.za')
            messages.success(request, 'The observer has been notified of the update.')
            return redirect('admin:applications:index')
        elif '_notify' not in request.POST:
            application.reject()
            application.save()
            messages.success(request, 'The application has been rejected.')
            return redirect('admin:applications:index')
    else:
        message = render_to_string('applications/saao/emails/rejected.txt', {
            'application': application
        })
        form = EmailForm(initial={
            'to': application.email,
            'cc': ','.join(a.email for a in application.applicants.all()
                if a.email != application.email),
            'subject': '[{}] Telescope Time Application'.format(
                application),
            'message': message,
        })
    return render(request, 'admin/applications/reject.html', {
        'application': application, 'form': form})


@login_required
def download(request, reference):
    if not (request.user.is_staff and
            request.user.has_perm('portal.view_application')):
        raise PermissionDenied

    application = get_object_or_404(Application, reference=reference)

    response = HttpResponse(content_type='applicaiton/pdf')
    response['Content-Disposition'] = 'attachment; filename="{}.pdf"'.format(application)

    buffer = application.as_pdf()
    pdf = buffer.getvalue()
    response.write(pdf)

    return response


@login_required
def rota(request):
    """Exports a 'ROTA' in CSV format."""

    if not (request.user.is_staff and
            request.user.has_perm('portal.view_application')):
        raise PermissionDenied

    applications = Application.objects.exclude(state='draft')
    if 'state' in request.GET:
        applications = applications.filter(state=request.GET['state'])
    if 'call' in request.GET:
        applications = applications.filter(call=request.GET['call'])

    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename="rota.csv"'

    writer = csv.writer(response)
    writer.writerow([
        'Week',  # This will be populated manually by an administrator.
        'Trimester',
        'Observers',
        'Principal Investigator',
        'Telescope',
        'Instrument',
        'Gratings/Filters',
        'Impossible Dates',
        'Requires Support',
    ])
    for application in applications:
        if application.is_support_required == True:
            requires_support = 'Yes'
        elif application.is_support_required == False:
            requires_support = 'No'
        else:
            # This field was added later and defaults to NULL so we can't know
            # whether they required support or not.
            requires_support = '-'

        writer.writerow([
            '',
            application.call,
            '/'.join(map(str, application.observers)),
            ' '.join([application.first_name.encode('utf-8'), application.last_name.encode('utf-8')]),
            application.telescope,
            application.instrument,
            application.gratings_filters.encode('utf-8'),
            application.dates_impossible,
            requires_support,
        ])

    return response

portal/admin/views/facilities.py
from django import forms
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.forms.models import modelform_factory
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from portal.admin.decorators import user_is_staff
from portal.models import Facility


decorators = [login_required, user_is_staff]


@method_decorator(decorators, name='dispatch')
class FacilityListView(ListView):
    model = Facility
    template_name = 'admin/facilities/index.html'
    context_object_name = 'facilities'
index = FacilityListView.as_view()


@method_decorator(decorators, name='dispatch')
class FacilityAddView(CreateView):
    model = Facility
    template_name = 'admin/facilities/add.html'
    fields = ('name', 'telescopes',)
    widgets = {
        'name': forms.TextInput(attrs={
            'class': 'form-control',
        }),
        'telescopes': forms.CheckboxSelectMultiple(),
    }

    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields, widgets=self.widgets)

    def form_valid(self, form):
        messages.success(self.request, 'The facility was added successfully.')
        return super(FacilityAddView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:facilities:edit', kwargs={'pk': self.object.id})
        return reverse('admin:facilities:index')
add = FacilityAddView.as_view()


@method_decorator(decorators, name='dispatch')
class FacilityEditView(UpdateView):
    model = Facility
    template_name = 'admin/facilities/edit.html'
    fields = ('name', 'telescopes',)
    widgets = {
        'name': forms.TextInput(attrs={
            'class': 'form-control',
        }),
        'telescopes': forms.CheckboxSelectMultiple(),
    }

    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields, widgets=self.widgets)

    def form_valid(self, form):
        messages.success(self.request, 'The facility was updated successfully.')
        return super(FacilityEditView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:facilities:edit', kwargs={'pk': self.object.id})
        return reverse('admin:facilities:index')
edit = FacilityEditView.as_view()

portal/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/static/css/fonts.css" rel="stylesheet" type="text/css">
    <link href="/static/css/AdminLTE.min.css" rel="stylesheet" type="text/css">
    <link href="/static/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css">
    <link href="/static/css/portal.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="/static/js/html5shiv.min.js"></script>
        <script src="/static/js/respond.min.js"></script>
    <![endif]-->
    {% block head %}{% endblock %}
</head>

<body class="skin-black {% if request.user.is_anonymous %}layout-top-nav{% else %}sidebar-mini{% endif %}" {% if '/admin/' in request.path %} style="border-top: 2px solid #dd4b39;"{% endif %}>
    {% block body %}
    <div class="wrapper">

        {% if not request.user.is_anonymous %}
        <header class="main-header">
            <a href="{% url 'dashboard' %}" class="logo hidden-xs"><strong>SAAO</strong></a>

            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle hidden-lg hidden-md hidden-sm" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        {% if request.user.is_superuser %}<li><a href="/docs/index.html">Help</a></li>{% endif %}
                        <li class="user user-menu"><a href="{% url 'profile' %}">
                            <span class="user-image">
                                {% if request.user.profile.avatar %}
                                <img src="{{ request.user.profile.avatar.url }}">
                                {% else %}
                                <img src="/static/img/avatar.png">
                                {% endif %}
                            </span>
                            <span class="hidden-xs">{{ request.user }}</span></a></li>
                        <li><a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-log-out hidden-lg hidden-md hidden-sm"></span>
                            <span class="hidden-xs">Sign out</span>
                        </a></li>
                    </ul>
                </div>
            </nav>
        </header>
        {% endif %}

        {% if not request.user.is_anonymous %}
        <aside class="main-sidebar">
            <section class="sidebar">
                {% block sidebar %}
                <ul class="sidebar-menu">
                    {% if perms.portal.add_application %}
                    <li class="header">OBSERVING</li>
                    <li{% if request.resolver_match.namespace == 'applications' %} class="active"{% endif %}>
                        <a href="{% url 'applications:index' %}"><span>Applications</span></a>
                    </li>
                    {% endif %}

                    {% if request.user.is_staff %}
                    <li class="header">OPERATIONS</li>
                    {% if perms.portal.view_application %}
                    <li{% if '/admin/applications' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:applications:index' %}">Applications</a>
                    </li>
                    {% endif %}
                    <li{% if '/admin/maintenance' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'maintenance:index' %}">Maintenance</a>
                    </li>

                    {% if request.user.is_superuser %}
                    <li{% if '/admin/telescopes' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:telescopes:index' %}">Telescopes</a>
                    </li>
                    <li{% if '/admin/instruments' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:instruments:index' %}">Instruments</a>
                    </li>
                    <li{% if '/admin/facilities' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:facilities:index' %}">Facilities</a>
                    </li>
                    {% endif %}

                    {% if perms.portal.add_call %}
                    <li{% if '/admin/calls' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:calls:index' %}">Calls</a>
                    </li>
                    {% endif %}

                    {% if request.user.is_superuser %}
                    <li{% if '/admin/users' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:users:index' %}">Users</a>
                    </li>
                    <li{% if '/admin/groups' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:groups:index' %}">Groups</a>
                    </li>
                    <li{% if '/admin/calendar' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:calendar' %}">Calendar</a>
                    </li>
                    <li class="header">INTERNALS</li>
                    <li{% if '/admin/sites' in request.path %} class="active"{% endif %}>
                        <a href="{% url 'admin:sites:index' %}">Sites</a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
                {% endblock %}
            </section>
        </aside>
        {% endif %}

        <div class="content-wrapper" style="margin-bottom: 15px;">
            {% if request.user.is_anonymous %}<div class="container">{% endif %}
                {% block header %}{% endblock %}

                <section class="content">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success{% endif %}">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% block content %}{% endblock %}
                </section>
            {% if request.user.is_anonymous %}</div>{% endif %}
        </div>

        <footer style="position: absolute; bottom: 0; right: 0; height: 50px; padding: 15px;">
            <div class="pull-right hidden-xs">
                Version {{ VERSION }}
            </div>
        </footer>

    </div>
    {% endblock %}

    {% block scripts %}
    <script type="text/javascript" src="/static/js/jQuery-2.1.4.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/application.js"></script>
    <script type="text/javascript">
    $('a.sidebar-toggle').click(function() {
        $('body').toggleClass('sidebar-open');
    });
    </script>
    {% endblock %}

</body>
</html>

portal/templates/instrument.html
{% extends "base.html" %}

{% block title %}
{{ instrument }} &mdash; {{ site.name }}
{% endblock %}

{% block header %}
{% if request.user.is_anonymous %}
<section class="content-header">
    <ol class="breadcrumb" style="float: none; position: initial;">
        <li><a href="/">Home</a></li>
        <li>Instruments</li>
        <li>{{ instrument }}</li>
    </ol>
</section>
{% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">

        <div class="box box-widget widget-user" style="">
            <div class="widget-user-header {% if instrument.is_available %}bg-green{% else %}bg-red{% endif %}" style="border-radius: 0">
                <h3 style="margin-top: 0;">{{ instrument }}</h3>
                {% if instrument.is_available %}
                All Systems Operational
                {% else %}
                {{ instrument.status }}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-md-3">
        {% if request.user.is_anonymous %}
        <a href="{% url 'login' %}" class="btn btn-primary btn-block">Sign in</a>
        <br>
        {% endif %}

        <div class="box box-solid visible-md visible-lg">
            <div class="box-header with-border">
                <h3 class="box-title">Telescopes</h3>
            </div>
            <div class="box-body no-padding">
                <ul class="nav nav-pills nav-stacked">
                    {% for telescope in telescopes %}
                    <li>
                        <a href="{% url 'telescope' pk=telescope.pk %}">
                            <span class="glyphicon {% if telescope.is_available %}glyphicon-ok-circle text-green{% else %}glyphicon-remove-circle text-red{% endif %}"></span>
                            {{ telescope }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="box box-solid visible-md visible-lg">
            <div class="box-header with-border">
                <h3 class="box-title">Instruments</h3>
            </div>
            <div class="box-body no-padding">
                <ul class="nav nav-pills nav-stacked">
                    {% for instrument in instruments %}
                    <li>
                        <a href="{% url 'instrument' pk=instrument.pk %}">
                            <span class="glyphicon {% if instrument.is_available %}glyphicon-ok-circle text-green{% else %}glyphicon-remove-circle text-red{% endif %}"></span>
                            {{ instrument }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}