it/urls.py
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls import include, url
from portal.views import profile
from portal.auth.forms import LoginForm


urlpatterns = [
    url(r'^', include(
        'portal.maintenance.urls', namespace='maintenance')),
    url(r'^profile/$', profile, name='profile'),

    url(r'^admin/', include('portal.maintenance.admin.urls', namespace='admin')),

    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/admin/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^applications/', include([
        url(r'^$', views.applications.index, name='index'),

        url(r'^(?P<pk>\d+)/', include([
            url(r'^$', views.applications.edit, name='edit'),
            url(r'^approve$', views.applications.approve, name='approve'),
            url(r'^reject$', views.applications.reject, name='reject'),
        ])),

        url(r'^(?P<reference>[^/]+).pdf$',
            views.applications.download, name='download'),
    ], namespace='applications')),

    url(r'^applications.csv', views.applications.rota, name='rota'),

    url(r'^facilities/', include([
        url(r'^$', views.facilities.index, name='index'),
        url(r'^new$', views.facilities.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.facilities.edit, name='edit'),
    ], namespace='facilities')),

    url(r'^call/new$', views.call_for_proposals, name='call_for_proposals'),

    url(r'calls/', include([
        url(r'^$', views.calls.index, name='index'),
        url(r'^new$', views.calls.add, name='add'),
        url(r'^(?P<pk>\d+)/', views.calls.edit, name='edit'),
    ], namespace='calls')),

    url(r'^telescopes/', include([
        url(r'^$', views.telescopes.index, name='index'),
        url(r'^new$', views.telescopes.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.telescopes.edit, name='edit'),
    ], namespace='telescopes')),

    url(r'^instruments/', include([
        url(r'^$', views.instruments.index, name='index'),
        url(r'^new$', views.instruments.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.instruments.edit, name='edit'),
    ], namespace='instruments')),

    url(r'^users/', include([
        url(r'^$', views.users.index, name='index'),
        url(r'^new$', views.users.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.users.edit, name='edit'),
    ], namespace='users')),

    url(r'^groups/', include([
        url(r'^$', views.groups.index, name='index'),
        url(r'^new$', views.groups.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.groups.edit, name='edit'),
    ], namespace='groups')),

    url(r'^sites/', include([
        url(r'^$', views.sites.index, name='index'),
        url(r'^new$', views.sites.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.sites.edit, name='edit'),
    ], namespace='sites')),

    # Only light pollution reports for now, but that might change later.
    url(r'^reports/', include([
        url(r'^new$', views.reports.create, name='create'),
    ], namespace='reports')),

    url(r'^calendar/$', views.calendar, name='calendar'),
]

portal/applications/urls.py
from django.conf.urls import include, url
from portal.applications import views


urlpatterns = [
    url(r'^$', views.applications, name='index'),
    url(r'^(?P<reference>[^/]+).pdf$', views.download, name='download'),

    url(r'^new$', views.create, name='new'),

    url(r'^(?P<facility>\w+)/', include([
        url(r'^new$', views.create, name='create'),
        url(r'^new/(?P<copy_from_pk>\d+)$', views.create, name='create'),
        url(r'^copy$', views.copy, name='copy'),
    ])),

    url(r'^(?P<pk>\d+)/', include([
        url(r'^$', views.update, name='update'),
        url(r'^submit$', views.submit, name='submit'),
    ])),
]

portal/auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import register, activate
from .forms import LoginForm


urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^activate/$', activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),

    url(r'^password_reset/$', views.password_reset,
        {'template_name': 'auth/password_reset_form.html',
            'email_template_name': 'auth/emails/password_reset.txt',
            'subject_template_name': 'auth/emails/password_reset_subject.txt'}, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        {'template_name': 'auth/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm,
        {'template_name': 'auth/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.password_reset_complete,
        {'template_name': 'auth/password_reset_complete.html'}, name='password_reset_complete'),
]

portal/urls.py
from django.conf import settings
from django.conf.urls import include, url
from portal import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^telescopes/(?P<pk>\d+)$', views.telescope, name='telescope'),
    url(r'^instruments/(?P<pk>\d+)$', views.instrument, name='instrument'),
    url(r'^applications/', include('portal.applications.urls', namespace='applications')),
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^admin/', include('portal.admin.urls', namespace='admin')),

    url(r'^admin/maintenance/', include(
        'portal.maintenance.urls', namespace='maintenance')),

    url(r'^', include('portal.auth.urls')),

    url(r'^o/authorize/$', views.AuthView.as_view(), name='authorize'),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/me$', views.ApiEndpoint.as_view()),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import os
import pytz

from polymorphic.models import PolymorphicModel
from django.db import models
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import python_2_unicode_compatible
from django_fsm import FSMField, transition


COUNTRIES = [
    ('AF', 'Afghanistan'),
    ('AX', 'Åland Islands'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AS', 'American Samoa'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AQ', 'Antarctica'),
    ('AG', 'Antigua and Barbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AW', 'Aruba'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrain'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BM', 'Bermuda'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia, Plurinational State of'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BW', 'Botswana'),
    ('BV', 'Bouvet Island'),
    ('BR', 'Brazil'),
    ('IO', 'British Indian Ocean Territory'),
    ('BN', 'Brunei Darussalam'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CA', 'Canada'),
    ('CV', 'Cabo Verde'),
    ('KY', 'Cayman Islands'),
    ('CF', 'Central African Republic'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CX', 'Christmas Island'),
    ('CC', 'Cocos (Keeling) Islands'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros'),
    ('CG', 'Congo'),
    ('CD', 'Congo, the Democratic Republic of the'),
    ('CK', 'Cook Islands'),
    ('CR', 'Costa Rica'),
    ('CI', 'Côte d\'Ivoire'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czech Republic'),
    ('DK', 'Denmark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('SV', 'El Salvador'),
    ('GQ', 'Equatorial Guinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('ET', 'Ethiopia'),
    ('FK', 'Falkland Islands (Malvinas)'),
    ('FO', 'Faroe Islands'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('GF', 'French Guiana'),
    ('PF', 'French Polynesia'),
    ('TF', 'French Southern Territories'),
    ('GA', 'Gabon'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Greece'),
    ('GL', 'Greenland'),
    ('GD', 'Grenada'),
    ('GP', 'Guadeloupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('HM', 'Heard Island and McDonald Islands'),
    ('VA', 'Holy See (Vatican City State)'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran, Islamic Republic of'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IM', 'Isle of Man'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('JE', 'Jersey'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KI', 'Kiribati'),
    ('KP', 'Korea, Democratic People\'s Republic of'),
    ('KR', 'Korea, Republic of'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Lao People\'s Democratic Republic'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macao'),
    ('MK', 'Macedonia, the former Yugoslav Republic of'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'Marshall Islands'),
    ('MQ', 'Martinique'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('YT', 'Mayotte'),
    ('MX', 'Mexico'),
    ('FM', 'Micronesia, Federated States of'),
    ('MD', 'Moldova, Republic of'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Morocco'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NC', 'New Caledonia'),
    ('NZ', 'New Zealand'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('NF', 'Norfolk Island'),
    ('MP', 'Northern Mariana Islands'),
    ('NO', 'Norway'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PW', 'Palau'),
    ('PS', 'Palestine, State of'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PN', 'Pitcairn'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RU', 'Russian Federation'),
    ('RW', 'Rwanda'),
    ('BL', 'Saint Barthélemy'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('KN', 'Saint Kitts and Nevis'),
    ('LC', 'Saint Lucia'),
    ('MF', 'Saint Martin (French part)'),
    ('PM', 'Saint Pierre and Miquelon'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Sao Tome and Principe'),
    ('SA', 'Saudi Arabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapore'),
    ('SX', 'Sint Maarten (Dutch part)'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'Solomon Islands'),
    ('SO', 'Somalia'),
    ('ZA', 'South Africa'),
    ('GS', 'South Georgia and the South Sandwich Islands'),
    ('SS', 'South Sudan'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudan'),
    ('SR', 'Suriname'),
    ('SJ', 'Svalbard and Jan Mayen'),
    ('SZ', 'Swaziland'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syrian Arab Republic'),
    ('TW', 'Taiwan, Province of China'),
    ('TJ', 'Tajikistan'),
    ('TZ', 'Tanzania, United Republic of'),
    ('TH', 'Thailand'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad and Tobago'),
    ('TN', 'Tunisia'),
    ('TR', 'Turkey'),
    ('TM', 'Turkmenistan'),
    ('TC', 'Turks and Caicos Islands'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('UM', 'United States Minor Outlying Islands'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela, Bolivarian Republic of'),
    ('VN', 'Viet Nam'),
    ('VG', 'Virgin Islands, British'),
    ('VI', 'Virgin Islands, U.S.'),
    ('WF', 'Wallis and Futuna'),
    ('EH', 'Western Sahara'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
]


class Address(models.Model):
    street = models.CharField('Street', max_length=255, null=True, blank=True)
    street2 = models.CharField('Street', max_length=255, null=True, blank=True)
    city = models.CharField('City', max_length=255, null=True, blank=True)
    postal_code = models.CharField('Postal Code', max_length=255, null=True, blank=True)
    country = models.CharField('Country', max_length=2, choices=COUNTRIES, null=True, blank=True)
    phone = models.CharField('Phone', max_length=255, null=True, blank=True)

    class Meta:
        abstract = True

    @property
    def postal_address(self):
        address_lines = [self.street]
        if self.street2:
            address_lines.append(self.street2)
        return ','.join(address_lines)


def get_avatar_name(instance, filename):
    filename = 'avatars/{}{}'.format(instance.user.id, os.path.splitext(filename)[1])
    filepath = os.path.join(settings.MEDIA_ROOT, filename)
    if os.path.exists(filepath):
        os.remove(filepath)
    return filename


@python_2_unicode_compatible
class Department(models.Model):
    class Meta:
        ordering = ['name']
        app_label = 'portal'

    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')
    head = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.name


class UserProfile(Address, models.Model):
    """User profile information.

    We define these properties in a separate model from the main User model to
    keep the auth app decoupled."""

    institution = models.CharField(max_length=255, blank=True, default='')

    dietary_requirements = models.CharField(
        max_length=255, blank=True, default='')
    timezone = models.CharField(max_length=64, default='UTC', choices=[
        (tz, tz) for tz in pytz.common_timezones])
    avatar = models.ImageField(
        upload_to=get_avatar_name, blank=True, null=True, default=None)

    department = models.ForeignKey('Department', blank=True, null=True)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')


@python_2_unicode_compatible
class Instrument(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=255)
    is_available = models.BooleanField(default=False)
    status = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Telescope(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=255)
    is_available = models.BooleanField(default=False)
    status = models.CharField(max_length=255, blank=True)

portal/templates/applications/saao/create.html
{% extends "base.html" %}

{% block title %}
New Application &mdash; {{ site.name }}
{% endblock %}

{% block head %}
<script>
var telescopes = {{ telescopes|safe }};
var instruments = {{ instruments|safe }};
</script>
{% endblock %}

{% block content %}
{% if form.errors or form.formsets.targets.errors or form.formsets.other_applications.errors or form.formsets.previous_applications.errors or form.formsets.applicants.errors %}
<div class="callout callout-danger">
    <p>Please correct the errors highlighted below and try again.</p>
</div>
{% else %}
<div class="callout callout-info">
    <p>You can <a href="{% url 'applications:copy' facility='SAAO' %}" style="color: #111;">create a copy of a previous application</a> for a quick start.
</div>
{% endif %}

<div class="box {% if form.errors or form.formsets.targets.errors or form.formsets.other_applications.errors or form.formsets.previous_applications.errors or form.formsets.applicants.errors %}box-danger{% else %}box-primary{% endif %}">

    <div class="box-header with-border">
        <h3 class="box-title">New Application</h3>
        <span class="text-muted pull-right">SAAO</span>
    </div>

    <form action="{% url 'applications:create' facility='SAAO' %}" method="post" enctype="multipart/form-data" role="form">
        {% include 'applications/saao/form.html' %}

        <div class="box-footer">
            <div class="pull-right">
                <input type="submit" value="Save Draft" name="draft" class="btn btn-default" style="margin-right: 1em;">
                <input type="submit" value="Submit for Approval" name="submit" class="btn btn-primary">
            </div>
        </div>
    </form>
</div>
{% endblock %}

portal/templates/applications/saao/decline.html
{% extends "base.html" %}

{% block title %}
Decline Allocation &mdash; {{ site.name }}
{% endblock %}

{% block content %}
<div class="callout callout-info">
    <p>If you would like to comment on your reasons for declining this allocation, you can do so below.</p>
</div>

<form action="{% url 'applications:decline' application_id=application.pk %}" method="post">
    {% csrf_token %}

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">{{ application.title }}</h3>
            <span class="pull-right">{{ application }}</span>
        </div>

        <div class="box-body" style="padding: 0;">
            {{ form.message }}
        </div>

        <div class="box-footer">
            <a href="{% url 'applications:edit' application_id=application.pk %}" class="btn" style="padding-left: 0;"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
            <button type="submit" class="btn btn-primary pull-right">Decline Allocation</button>
        </div>
    </div>
</form>
{% endblock %}

portal/templates/applications/saao/update.html
{% extends "base.html" %}

{% block title %}
{{ application.title }} &mdash; {{ site.name }}
{% endblock %}

{% block head %}
<script>
var telescopes = {{ telescopes|safe }};
var instruments = {{ instruments|safe }};
</script>
{% endblock %}

{% block content %}
{% if form.errors or form.formsets.targets.errors or form.formsets.other_applications.errors or form.formsets.previous_applications.errors or form.formsets.applicants.errors %}
<div class="callout callout-danger">
    <p>Please correct the errors highlighted below and try again.</p>
</div>
{% endif %}

<div class="box {% if form.errors or form.formsets.targets.errors or form.formsets.other_applications.errors or form.formsets.previous_applications.errors or form.formsets.applicants.errors %}box-danger{% else %}box-primary{% endif %}">

    <div class="box-header with-border">
        <h3 class="box-title">{{ application.title }}</h3>
        <span class="text-muted pull-right">{{ application.facility }}</span>
    </div>

    <form action="{% url 'applications:update' pk=application.pk %}" method="post" enctype="multipart/form-data" role="form">
        {% include 'applications/saao/form.html' %}

        <div class="box-footer">
            <div class="pull-right">
                <input type="submit" value="Save Draft" name="draft" class="btn btn-default" style="margin-right: 1em;">
                <input type="submit" value="Submit for Approval" name="submit" class="btn btn-primary">
            </div>
            <input type="button" value="Delete Draft" name="delete" class="btn btn-danger" data-toggle="modal" data-target="#delete-draft">
        </div>
    </form>
</div>

<div id="delete-draft" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete Application</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure that you want to delete this application?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
                <form action="{% url 'applications:update' pk=application.pk %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" value="Delete Draft" name="delete" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}