it/urls.py
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls import include, url
from portal.views import profile
from portal.auth.forms import LoginForm


urlpatterns = [
    url(r'^', include(
        'portal.maintenance.urls', namespace='maintenance')),
    url(r'^profile/$', profile, name='profile'),

    url(r'^admin/', include('portal.maintenance.admin.urls', namespace='admin')),

    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/admin/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^applications/', include([
        url(r'^$', views.applications.index, name='index'),

        url(r'^(?P<pk>\d+)/', include([
            url(r'^$', views.applications.edit, name='edit'),
            url(r'^approve$', views.applications.approve, name='approve'),
            url(r'^reject$', views.applications.reject, name='reject'),
        ])),

        url(r'^(?P<reference>[^/]+).pdf$',
            views.applications.download, name='download'),
    ], namespace='applications')),

    url(r'^applications.csv', views.applications.rota, name='rota'),

    url(r'^facilities/', include([
        url(r'^$', views.facilities.index, name='index'),
        url(r'^new$', views.facilities.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.facilities.edit, name='edit'),
    ], namespace='facilities')),

    url(r'^call/new$', views.call_for_proposals, name='call_for_proposals'),

    url(r'calls/', include([
        url(r'^$', views.calls.index, name='index'),
        url(r'^new$', views.calls.add, name='add'),
        url(r'^(?P<pk>\d+)/', views.calls.edit, name='edit'),
    ], namespace='calls')),

    url(r'^telescopes/', include([
        url(r'^$', views.telescopes.index, name='index'),
        url(r'^new$', views.telescopes.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.telescopes.edit, name='edit'),
    ], namespace='telescopes')),

    url(r'^instruments/', include([
        url(r'^$', views.instruments.index, name='index'),
        url(r'^new$', views.instruments.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.instruments.edit, name='edit'),
    ], namespace='instruments')),

    url(r'^users/', include([
        url(r'^$', views.users.index, name='index'),
        url(r'^new$', views.users.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.users.edit, name='edit'),
    ], namespace='users')),

    url(r'^groups/', include([
        url(r'^$', views.groups.index, name='index'),
        url(r'^new$', views.groups.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.groups.edit, name='edit'),
    ], namespace='groups')),

    url(r'^sites/', include([
        url(r'^$', views.sites.index, name='index'),
        url(r'^new$', views.sites.add, name='add'),
        url(r'^(?P<pk>\d+)/$', views.sites.edit, name='edit'),
    ], namespace='sites')),

    # Only light pollution reports for now, but that might change later.
    url(r'^reports/', include([
        url(r'^new$', views.reports.create, name='create'),
    ], namespace='reports')),

    url(r'^calendar/$', views.calendar, name='calendar'),
]

portal/applications/urls.py
from django.conf.urls import include, url
from portal.applications import views


urlpatterns = [
    url(r'^$', views.applications, name='index'),
    url(r'^(?P<reference>[^/]+).pdf$', views.download, name='download'),

    url(r'^new$', views.create, name='new'),

    url(r'^(?P<facility>\w+)/', include([
        url(r'^new$', views.create, name='create'),
        url(r'^new/(?P<copy_from_pk>\d+)$', views.create, name='create'),
        url(r'^copy$', views.copy, name='copy'),
    ])),

    url(r'^(?P<pk>\d+)/', include([
        url(r'^$', views.update, name='update'),
        url(r'^submit$', views.submit, name='submit'),
    ])),
]

portal/auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import register, activate
from .forms import LoginForm


urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^activate/$', activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),

    url(r'^password_reset/$', views.password_reset,
        {'template_name': 'auth/password_reset_form.html',
            'email_template_name': 'auth/emails/password_reset.txt',
            'subject_template_name': 'auth/emails/password_reset_subject.txt'}, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        {'template_name': 'auth/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm,
        {'template_name': 'auth/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.password_reset_complete,
        {'template_name': 'auth/password_reset_complete.html'}, name='password_reset_complete'),
]

portal/urls.py
from django.conf import settings
from django.conf.urls import include, url
from portal import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^telescopes/(?P<pk>\d+)$', views.telescope, name='telescope'),
    url(r'^instruments/(?P<pk>\d+)$', views.instrument, name='instrument'),
    url(r'^applications/', include('portal.applications.urls', namespace='applications')),
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^admin/', include('portal.admin.urls', namespace='admin')),

    url(r'^admin/maintenance/', include(
        'portal.maintenance.urls', namespace='maintenance')),

    url(r'^', include('portal.auth.urls')),

    url(r'^o/authorize/$', views.AuthView.as_view(), name='authorize'),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/me$', views.ApiEndpoint.as_view()),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

sites/admin/urls.py
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls import include, url
from portal.views import profile
from portal.admin.views import users, departments, groups
from portal.auth.forms import LoginForm
from sites.admin.views import dashboard


urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^profile/$', profile, name='profile'),

    url(r'^students/', include('sites.admin.students.urls', namespace='students')),

    url(r'^admin/', include([
        url(r'^students/', include('sites.admin.students.admin.urls', namespace='students')),

        url(r'^users/', include([
            url(r'^$', users.index, name='index'),
            url(r'^new$', users.add, name='add'),
            url(r'^(?P<pk>\d+)/$', users.edit, name='edit'),
        ], namespace='users')),

        url(r'^departments/', include([
            url(r'^$', departments.index, name='index'),
            url(r'^new$', departments.create, name='create'),
            url(r'^(?P<pk>\d+)/$', departments.update, name='update'),
        ], namespace='departments')),

        url(r'^groups/', include([
            url(r'^$', groups.index, name='index'),
            url(r'^new$', groups.add, name='add'),
            url(r'^(?P<pk>\d+)/$', groups.edit, name='edit'),
        ], namespace='groups')),
    ], namespace='admin')),

    url(r'^login/$', views.login,
        {'template_name': 'auth/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
]


if settings.DEBUG:
    from django.views import static
    from django.views.generic.base import TemplateView
    urlpatterns += [
        url(r'^403$', TemplateView.as_view(template_name='403.html')),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
        url(r'^docs/(?P<path>.*)$', static.serve, {
            'document_root': 'docs/_build/html/',
        }),
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
   ]

portal/forms.py
from django import forms
from portal.auth.models import User
from portal.models import UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']
        labels = {
            'postal_code': 'Zip / Postal Code',
            # Form labels need to be title-cased for consistency.
            'timezone': 'Time Zone',
        }
        widgets = {
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'street2': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.Select(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'institution': forms.TextInput(attrs={'class': 'form-control'}),
            'department': forms.Select(attrs={'class': 'form-control'}),
            'timezone': forms.Select(attrs={'class': 'form-control'}),
        }

portal/admin/views/calls.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from portal.admin.decorators import user_is_staff
from portal.admin.forms import CallForProposalsForm
from portal.models import Call, Facility


decorators = [
    login_required,
    user_is_staff,
    permission_required('portal.add_call', raise_exception=True)
]


@method_decorator(decorators, name='dispatch')
class CallListView(ListView):
    model = Call
    template_name = 'admin/calls/index.html'
    context_object_name = 'calls'

    def get_context_data(self, **kwargs):
        context = super(CallListView, self).get_context_data(**kwargs)
        context['facilities'] = Facility.objects.all()
        return context

    def get_queryset(self):
        if 'facility' in self.request.GET:
            try:
                facility = Facility.objects.get(pk=self.request.GET['facility'])
            except Facility.DoesNotExist:
                calls = []
            else:
                calls = facility.calls.all()
        else:
            calls = Call.objects.all()
        return calls
index = CallListView.as_view()


@method_decorator(decorators, name='dispatch')
class CallAddView(CreateView):
    model = Call
    template_name = 'admin/calls/add.html'
    form_class = CallForProposalsForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        messages.success(self.request, 'The call was added successfully.')
        return super(CallAddView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:calls:edit', kwargs={'pk': self.object.pk})
        return reverse('admin:calls:index')
add = CallAddView.as_view()


@method_decorator(decorators, name='dispatch')
class CallEditView(UpdateView):
    model = Call
    template_name = 'admin/calls/edit.html'
    form_class = CallForProposalsForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'delete' in request.POST:
            if len(self.object.applications.all()) > 0:
                messages.error(request, 'The call cannot be deleted. It has '
                    'applications associated with it.')
                return HttpResponseRedirect(
                    reverse('admin:calls:edit', kwargs={'pk': self.object.pk}))
            self.object.delete()
            messages.success(request, 'The call was deleted.')
            return HttpResponseRedirect(self.get_success_url())
        return super(CallEditView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, 'The call was updated successfully.')
        return super(CallEditView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:calls:edit', kwargs={'pk': self.object.pk})
        return reverse('admin:calls:index')
edit = CallEditView.as_view()

portal/admin/views/departments.py
from django import forms
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.forms.models import modelform_factory
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from portal.admin.decorators import user_is_staff
from portal.models import Department


decorators = [
    login_required,
    user_is_staff,

    # We're intentionally using a non-existent permission so that only
    # superusers can access the department admin.
    permission_required('portal.manage_departments', raise_exception=True)
]


@method_decorator(decorators, name='dispatch')
class DepartmentListView(ListView):
    model = Department
    template_name = 'admin/departments/index.html'
    context_object_name = 'departments'
index = DepartmentListView.as_view()


@method_decorator(decorators, name='dispatch')
class DepartmentCreateView(CreateView):
    model = Department
    template_name = 'admin/departments/create.html'
    fields = ('name', 'parent', 'head',)
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'parent': forms.Select(attrs={'class': 'form-control'}),
        'head': forms.Select(attrs={'class': 'form-control'}),
    }

    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields,
            widgets=self.widgets)

    def form_valid(self, form):
        messages.success(self.request, 'The department was added successfully.')
        return super(DepartmentCreateView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:departments:update', kwargs={'pk': self.object.pk})
        return reverse('admin:departments:index')
create = DepartmentCreateView.as_view()


@method_decorator(decorators, name='dispatch')
class DepartmentUpdateView(UpdateView):
    model = Department
    template_name = 'admin/departments/update.html'
    fields = ('name', 'parent', 'head',)
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'parent': forms.Select(attrs={'class': 'form-control'}),
        'head': forms.Select(attrs={'class': 'form-control'}),
    }

    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields,
            widgets=self.widgets)

    def form_valid(self, form):
        messages.success(self.request, 'The department was updated successfully.')
        return super(DepartmentUpdateView, self).form_valid(form)

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('admin:departments:update', kwargs={'pk': self.object.pk})
        return reverse('admin:departments:index')
update = DepartmentUpdateView.as_view()

portal/templates/applications/copy.html
{% extends "base.html" %}

{% block title %}
Copy Application &mdash; {{ site.name }}
{% endblock %}

{% block content %}
{% if applications %}
<div class="callout callout-info">
    <p>Please select the application that you would like to make a copy of.</p>
</div>

<div class="box">
    <div class="box-body no-padding table-responsive">
        <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Telescope</th>
                <th>Instrument</th>
            </tr>
        </thead>
        <tbody>
            {% for application in applications %}
            <tr>
                <td>
                    <a href="{% url 'applications:create' facility=application.facility copy_from_pk=application.pk %}">{{ application.title }}</a>
                </td>
                <td>{{ application.telescope }}</td>
                <td>{{ application.instrument }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
</div>
{% else %}
<h3 class="text-muted" style="text-align: center;">You don't have any previous applications to copy.</h3>
{% endif %}
{% endblock %}

portal/templates/applications/create.html
{% extends "base.html" %}

{% block title %}
New Application &mdash; {{ site.name }}
{% endblock %}

{% block content %}
<div class="callout callout-info">
    <p>Please select the facility that you want to apply to below.</p>
</div>

<div class="row callout">
    <div style="float: left;">
        <h4><a href="http://www.saao.ac.za" style="color: #000; text-decoration: none;"><strong>SAAO</strong></a></h4>
        <p class="text-muted hidden-sm hidden-xs">Includes IRSF, 40-inch, 74-inch and Lesedi telescopes.</p>
    </div>
    <a href="{% url 'applications:create' facility='SAAO' %}" class="btn btn-success pull-right" style="text-decoration: none;">Create a new application</a>
</div>

<div class="row callout">
    <div style="float: left;">
        <h4><a href="http://lcogt.net" style="color: #000; text-decoration: none; font-size: 18px;"><strong>LCO</strong></a></h4>
        <p class="text-muted hidden-sm hidden-xs">The SAAO has 300 hours per semester of observing time on the 1-m class network (North and South).</p>
    </div>
    <a href="{% url 'applications:create' facility='LCO' %}" class="btn btn-success pull-right" style="text-decoration: none;">Create a new application</a>
</div>

<div class="row callout">
    <div style="float: left;">
        <h4><a href="http://kmtnet.kasi.re.kr" style="color: #000; text-decoration: none; font-size: 18px;"><strong>KMTNET</strong></a></h4>
        <p class="text-muted hidden-sm hidden-xs">The SAAO has 307 hours of observing time on the 1.6-m wide field (2&deg; x 2&deg;) telescope.</p>
    </div>
    <a href="{% url 'applications:create' facility='KMTNET' %}" class="btn btn-success pull-right" style="text-decoration: none;">Create a new application</a>
</div>
{% endblock %}

portal/templates/applications/index.html
{% extends "base.html" %}

{% block title %}
Applications &mdash; {{ site.name }}
{% endblock %}

{% block content %}
    {% if not applications and not request.GET.state %}
        <h3 class="text-muted" style="text-align: center;">It looks like you haven't applied for time on one of our telescopes yet. Would you like to <a href="{% url 'applications:new' %}">apply now</a>?</h3>
    {% else %}
    <div class="row">

        <div class="col-md-3 col-md-push-9">
            <a href="{% url 'applications:new' %}" class="btn btn-block margin-bottom" style="font-size: 16px; font-weight: bold;">New Application</a>
            <div class="box box-solid visible-md visible-lg">
                <div class="box-body no-padding">
                    <ul class="nav nav-pills nav-stacked">
                        <li{% if not request.GET.state %} class="active"{% endif %}>
                            <a href="{% url 'applications:index' %}">All Applications</a>
                        </li>
                        <li{% if request.GET.state and request.GET.state == 'submitted' %} class="active"{% endif %}>
                            <a href="{% url 'applications:index' %}?state=submitted">Submitted</a>
                        </li>
                        <li{% if request.GET.state and request.GET.state == 'approved' %} class="active"{% endif %}>
                            <a href="{% url 'applications:index' %}?state=approved">Approved</a>
                        </li>
                        <li{% if request.GET.state and request.GET.state == 'rejected' %} class="active"{% endif %}>
                            <a href="{% url 'applications:index' %}?state=rejected">Rejected</a>
                        </li>
                        <li{% if request.GET.state and request.GET.state == 'draft' %} class="active"{% endif %}>
                            <a href="{% url 'applications:index' %}?state=draft">Drafts</a>
                        </li>
                    </ul>
                </div>
            </div>

            {% if facilities.count > 1 %}
            <div class="box box-solid visible-md visible-lg">
                <div class="box-body no-padding">
                    <ul class="nav nav-pills nav-stacked">
                    {% for facility in facilities %}
                        <li{% if request.GET.facility and request.GET.facility == facility.pk|stringformat:'i' %} class="active"{% endif %}>
                            <a href="?facility={{ facility.id }}{% for k,v in request.GET.iteritems %}{% if k != 'facility' %}&amp;{{ k }}={{ v }}{% endif %}{% endfor %}">{{ facility }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="col-md-9 col-md-pull-3">
            {% if applications %}
            <div class="box">
                <div class="box-body no-padding table-responsive">
                    <table class="table">
                    <thead>
                        <tr>
                            <th class="hidden-xs hidden-sm hidden-md" style="width: 50px;">&nbsp;</th>
                            <th>Title</th>
                            <th>Telescope</th>
                            <th>Instrument</th>
                            <th style="text-align: right;">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for application in applications %}
                        <tr>
                            <td class="hidden-xs hidden-sm hidden-md">
                                {% if application.reference %}
                                <a href="{% url 'applications:download' reference=application.reference %}" title="Download Application"><span class="label" style="color: crimson;"><span class="glyphicon glyphicon-file"></span> PDF</span></a>
                                {% endif %}
                            </td>
                            <td style="white-space: nowrap; width: 300px; overflow: hidden; text-overflow: ellipsis; max-width: 300px;"><a href="{% url 'applications:update' pk=application.pk %}" title="{{ application.title }}">{{ application.title }}</a></td>
                            <td>{{ application.telescope }}</td>
                            <td>{{ application.instrument }}</td>
                            <td style="text-align: right;">
                            <span class="label 
                            {% if application.state == 'draft' %}
                                text-muted
                            {% elif application.state == 'submitted' %}
                                text-light-blue
                            {% elif application.state == 'approved' or application.state == 'accepted' %}
                                text-green
                            {% elif application.state == 'rejected' or application.state == 'declined' %}
                                text-red
                            {% endif %}
                            ">{{ application.state|upper }}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
            {% else %}
                <h3 class="text-muted text-center">No Applications Available</h3>
            {% endif %}
        </div>
    </div>
    {% endif %}
{% endblock %}